ユーザー登録機能とユーザー編集機能の修正
popotarosan/e-navigator pull request #2
Opened 2019-03-10 06:33 UTC by popotarosan

やりたかったこと
- 前回のプルリクエストに対するレビューの修正
    - Production環境でユーザー登録できるようにする
    - ユーザー取得関数のDRY化
    - インデントの修正

やったこと
- Productionのconfigのconfig.action_mailer.default_url_optionsのhost名の修正
- ユーザー編集・更新時、ユーザー取得をするためのコールバック関数の作成
- 上記の関数をbefore_actionに追加

動作確認方法
- ユーザーを登録機能
    - サインアップ
    - 届いたメールのURLにアクセス
    - ログイン
- ユーザー編集をする

2019-03-12 04:02 UTC, pokotyamu commented
タイトル良くなりましたね 😄 
そんな感じで次も付けていってください 👍

2019-03-12 04:03 UTC, pokotyamu requested changes
@popotarosan 
config の部分は修正が必要だと思うのでよろしくおねがいします 🙏 
あとインデントの件も意図が無ければないでいいので、返信していただけると 🙏

2019-03-12 04:03 UTC, pokotyamu commented on config/environments/production.rb
> +  on boot. This eager loads most of Rails and
コメントの途中で改行しているから、変な感じになってないかな？ 👀

2019-03-12 04:03 UTC, pokotyamu commented on config/environments/production.rb
> +  config.action_mailer.raise_delivery_errors = false
メーラーのコメントの変更も、 `[update]ユーザー取得のDRY化` に関係している内容なんだろうか？ 🤔 
多分、関係ないと思うので、これは別のコミットとして分けた方が良かったかも知れませんね 😓

2019-03-12 04:03 UTC, pokotyamu commented on app/controllers/users_controller.rb
> +                                 :school_name)
結局、ここ `school_name` だけ改行しているのはなんでなんですか？ 
どんな基準で改行しているかを教えて欲しいです。
see: https://github.com/popotarosan/e-navigator/pull/1#discussion_r260611473

2019-03-12 06:08 UTC, merged

2019-03-12 06:08 UTC, popotarosan commented on app/controllers/users_controller.rb
> +                                 :school_name)
意味はないです。１行に修正しました。

2019-03-13 02:22 UTC, pokotyamu commented on app/controllers/users_controller.rb
> +                                 :school_name)
なるほど 🙏 
一応 ruby の世界にはコーディング規約がないので、以下を参考にしてみると良いかと思いました！
https://www.ruby.or.jp/ja/tech/development/ruby/050_coding_rule.html