Feature/implement edit and delete interview schedule function
popotarosan/e-navigator pull request #5
Opened 2019-04-02 12:39 UTC by popotarosan

やりたかったこと
- 面接日程の編集機能
- 面接日程の削除機能

やったこと
- Interviewsコントローラーのedit,deleteメソッドの実装
- 面接編集ページの作成
- 面接一覧ページの修正
- レイアウトに自分の面接一覧へのリンク追加

動作確認方法
- ログインする
- 面接を登録する
- 面接一覧画面から編集する
- 面接一覧画面から削除する

2019-04-05 02:36 UTC, pokotyamu commented
> Feature/implement edit and delete interview schedule function

ブランチ名とタイトルが一緒なのは意図的です？ 👀

2019-04-05 02:43 UTC, pokotyamu requested changes
遅くなってしまってすみません 🙇 
レビューコメントつけました！確認よろしくおねがいします！

2019-04-05 02:43 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    @interview = current_user.interviews.find(params[:id])
> @interview = current_user.interviews.find(params[:id])    

複数箇所で、この定義してますね 👀 
Rails の DRY 原則に従って、一箇所にまとめてしまいましょう！

`private` メソッドで、 `set_interview` とするのはどうでしょうか？ 😄

2019-04-05 02:43 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    @interview = current_user.interviews.find(params[:id])
ちなみに、 `current_user.interviews.find(params[:id])` を `Interview.find(params[:id])` とも書けると思うんですが、 `current_user` を経由する必要ありますかね？ 👀

2019-04-05 02:43 UTC, pokotyamu commented on app/views/interviews/edit.html.erb
> +<% end %>
ここ末尾改行が抜けてますね。
エディターの設定に入れておきましょう！

[ソースコードの最後に改行を入れる - かまたま日記3](https://kamatama41.hatenablog.com/entry/2015/09/10/194414)

2019-04-05 03:52 UTC, popotarosan commented
> > Feature/implement edit and delete interview schedule function
> 
> ブランチ名とタイトルが一緒なのは意図的です？ 👀
意図的ではありません。設定し忘れました。修正いたしました。

2019-04-05 05:19 UTC, pokotyamu commented
修正内容としては問題ないと思いました 👌 
動作的にも問題ないと思います！

これの質問は答えられたら、よろしくおねがいします 🙏 
https://github.com/popotarosan/e-navigator/pull/5#discussion_r272429261

2019-04-05 05:20 UTC, pokotyamu approved these changes
LGTM 👌 
このプルリクエストはマージして次に進めて大丈夫そうです！

2019-04-06 04:09 UTC, popotarosan commented on app/controllers/interviews_controller.rb
> +    @interview = current_user.interviews.find(params[:id])
必要ありませんでした。
params[:id]で一意的にinterviewモデルのインスタンスが決まるので。

2019-04-06 04:10 UTC, merged